name: ページ更新

# mainブランチへのプッシュがトリガー
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # ubuntu最終環境で実行
    runs-on: ubuntu-latest

    steps:
      # リポジトリからコードをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v3

      # Node.js ver.20.11.0をセットアップ
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.11.0'

      # プロジェクトのあるproディレクトリへ移動
      # 依存環境をインストール
    - name: Install dependencies
      working-directory: pro
      run: npm install

      # Firebaseの設定を.envファイルに注入
    - name: Inject Firebase Config
      working-directory: pro
      run: |
        echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> .env
        echo "REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> .env
        echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}" >> .env
        echo "REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}" >> .env
        echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
        echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}" >> .env
        echo "REACT_APP_FIREBASE_MEASUREMENT_ID=${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}" >> .env

      # プロジェクトをビルド
    - name: Build the project
      working-directory: pro
      run: npm run build

    - name: Githubページにデプロイ
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: pro/build
